name: Nueva Issue de desarrollo
description: Usa esta plantilla para registrar un Issue relacionado a un ticket del CRM Smart Strategy Quickbase
title: "[CRM#xxxx] Breve descripci칩n del caso"
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### 游빐 Pol칤tica interna de Issues Smart Strategy
        Antes de continuar, aseg칰rate de cumplir con las reglas del [Manual de Buenas Pr치cticas de Issues](../docs/ISSUE_POLICY.md).

        **Resumen r치pido:**
        - Toda Issue debe vincularse a un ticket del CRM Smart Strategy Quickbase.  
        - El t칤tulo debe seguir el formato `[CRM#XXXX] descripci칩n`.  
        - Se debe asignar responsable y etiquetas correspondientes.  
        - Los commits deben incluir `Fixes #<n칰mero>` o `Ref #<n칰mero>`.

  - type: input
    id: ticket
    attributes:
      label: Ticket CRM relacionado
      description: Indica el n칰mero o enlace del ticket en CRM Smart Strategy Quickbase
      placeholder: "CRM#1234"
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label: Descripci칩n del caso
      description: Describe claramente el problema o mejora detectada
      placeholder: |
        Describe aqu칤 el contexto, pasos para reproducir, resultado actual y esperado.
    validations:
      required: true
